[package]
name = "rvtools2vse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
anyhow = "1.0.58"
office = "0.8.1"
itertools = "0.10.5"
